---

- name: configure pgbouncer settings
  ini_file:
    dest: "{{ pgbouncer_config_path }}"
    section: "{{ item.section | default('pgbouncer') }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items: "{{ pgbouncer_config }}"
  when: "pgbouncer_config is defined"
  notify: reload pgbouncer

- name: start pgbouncer
  service:
    name: pgbouncer
    state: started
